---

- name: find local public ssh key and register it's contents
  slurp:
    src: "{{ lookup('first_found', ssh_local_public_keys_locations) }}"
  register: ssh_key
  become: false
  delegate_to: localhost

- include_tasks: pool.yml
  when: (cleanup_vms is not defined) or (cleanup_vms == False)

- include_tasks: network.yml 
  when: (cleanup_vms is not defined) or (cleanup_vms == False)

- include_tasks: launch_vms.yml
  loop: "{{ range(1, libvirt_trex_vm_count+1)|list }}"
  when: (cleanup_vms is not defined) or (cleanup_vms == False)

- block:
  - include_tasks: cleanup.yml
    loop: "{{ range(1, libvirt_trex_vm_count+1)|list }}"
    tags: [ cleanup ]
  - fail:
      msg="Stopping Playbook after removing all VMs (cleanup)"
    tags: [ cleanup ]
  when: (cleanup_vms is defined) and (cleanup_vms == True)
   
