---

- name: generate sequence for launching vms
  set_fact:
    vm_sequence: "{{ range(1, libvirt_trex_vm_count+1) | list }}"

- include_tasks: pool.yml

- include_tasks: network.yml

- include_tasks: start_vm.yml
  loop: "{{ vm_sequence }}"
  loop_control:
    index_var: vm
  when: (cleanup_vms is not defined) or (cleanup_vms == False)

- include_tasks: cleanup.yml
  loop: "{{ vm_sequence }}"
  loop_control:
    index_var: vm
  when: (cleanup_vms is defined) and (cleanup_vms == True)

