---

- name: install kernel headers on debian based systems
  apt:
    name: linux-headers-{{ ansible_kernel }}
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600

- name: install build-essential meta package
  apt:
    name: build-essential
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600

- name: install python3-distutils
  apt:
    name: python3-distutils
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600
