---

- name: include distribution specific setup
  include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "include_{{ ansible_distribution }}.yaml"
        - "include_{{ ansible_os_family }}.yaml"
      paths: [ '.' ]

- name: create trex folder
  file:
    path: /opt/trex-v{{ trex_version }}
    state: directory

- name: grab trex release
  get_url:
    url: "{{ trex_release_url }}"
    dest: /opt/trex-v{{ trex_version }}.tar.gz

- name: unarchive trex release
  unarchive:
    src: /opt/trex-v{{ trex_version }}.tar.gz
    dest: /opt/trex-v{{ trex_version }}
    remote_src: yes
    extra_opts: [ "--strip-components", "1" ]
    creates: /opt/trex-v{{ trex_version}}/t-rex-64
    owner: root
    group: root

- name: add /opt/trex symlink
  file:
    state: link
    src: trex-v{{ trex_version }}
    path: /opt/trex

- name: generating trex configuration
  template:
    src: trex_cfg.yaml.j2
    dest: /etc/trex_cfg.yaml
  notify: restart trex

- name: generating trex systemd unit
  template:
    src: trex_service.j2
    dest: /etc/systemd/system/trex.service
    mode: 0644
  notify: restart trex

- name: enable and start trex
  systemd:
    name: trex
    daemon_reload: yes
    state: started
    enabled: yes
    masked: no
