---

- name: prefetch trex docker image
  docker_image:
    name: "{{ trex_docker_image }}"
    state: present
    force_source: yes
    source: pull

- name: generation trex configuration
  template:
    src: trex_cfg.yaml.j2
    dest: /etc/trex_cfg.yaml

  # we must have properly installed kernel-headers in /usr/src/ and linked in 
  # /lib/modules/`uname -r`/build
- name: start fully privileged container with TRex in interactive mode
  docker_container:
    name: "trex-server"
    hostname: "{{ ansible_hostname }}-trex-i"
    image: "{{ trex_docker_image }}"
    capabilities: [ all ]
    privileged: "yes"
    recreate: "{{ trex_force_recreate | default('false') }}"
    state: "{{ trex_force_state | default('started') }}"
    restart_policy: "no"
    init: "yes"
    published_ports: "{{ trex_docker_published_ports }}"
    volumes:
      - /etc/trex_cfg.yaml:/etc/trex_cfg.yaml:ro
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
      - /sys/bus/pci/devices:/sys/bus/pci/devices
      - /sys/devices/system/node:/sys/devices/system/node
      - /dev:/dev
