---

- name: install kernel headers and modules on Fedora
  yum:
    name:
      - kernel-devel-{{ ansible_kernel }}
      - kernel-modules-{{ ansible_kernel }}
    state: present

- name: install python2-pip
  yum:
    name: python2-pip
    state: present
  when: ansible_python_version is version('3', '<')

- name: install python3-pip
  yum:
    name: python3-pip
    state: present
  when: ansible_python_version is version('3', '>=')

