---

- name: install kernel headers on Debian based systems
  apt:
    name: linux-headers-{{ ansible_kernel }}
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600

- name: install python-pip
  apt:
    name: python-pip
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600
  when: ansible_python_version is version('3', '<')

- name: install python3-pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600
  when: ansible_python_version is version('3', '>=')

