---

- name: include distribution specific setup
  include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "include_{{ ansible_distribution }}.yaml"
        - "include_{{ ansible_os_family }}.yaml"
      paths: [ '.' ]
