---

- name: install libvirt on debian systems
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon
      - python-libvirt
      - python-lxml
      - bridge-utils
      - libvirt-clients
      - cloud-image-utils
      - libvirt-daemon-system      
    state: present
  when: ansible_os_family == "Debian"

- name: install libvirt on redhat systems
  yum:
    name:
      - qemu-kvm
      - libvirt
      - libvirt-python
      - bridge-utils
      - python-lxml
      - cloud-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: symlink kvm-spice on centos
  file:
    state: link
    src: kvm
    dest: /usr/bin/kvm-spice
  when: ansible_distribution == "CentOS"


- name: enable libvirtd daemon
  systemd:
    name: libvirtd
    daemon_reload: yes
    enabled: yes
    state: started
    masked: no
