---

- name: install required packages for docker
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
    update_cache: no

- name: add repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/{{ ansible_distribution|lower }}/{{ ansible_distribution_major_version }}/$basearch/stable
    gpgkey: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg

- name: install docker
  yum:
    name: [ docker-ce, docker-ce-cli, containerd.io ]
    state: present
    update_cache: yes

- name: install python wrapper for docker
  pip:
    name: docker
    state: present
