---

- name: Gather facts always, regardless of tags
  hosts: libvirt
  roles:
    - { role: checks, tags: [ checks ] }
  tags: [ always ]

- name: Launch TRex libvirt virtual machines
  hosts: libvirt
  become: true
  roles:
    - { role: libvirt, tags: [ libvirt ] }
  tags: [ always ]

- name: Set up newly created VMs
  hosts: libvirt_vms
  become: true
  tasks:
    - command: hostname
      register: debug
    - debug:
        msg: "{{ debug.stdout }}"
  roles:
    - { role: common, tags: [ common ] }
    #- { role: docker, tags: [ docker ] }
